//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad
    {
        public ad()
        {
            this.newspapers = new HashSet<newspaper>();
        }
    
        public int ad_id { get; set; }
        public string ad_name { get; set; }
        public string ad_content { get; set; }
    
        public virtual ICollection<newspaper> newspapers { get; set; }
    }
}
